services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  db:
    image: public.ecr.aws/docker/library/postgres:16-bullseye
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  user-service:
    build:
      context: .
      dockerfile: user/Dockerfile
    depends_on:
      - db
    environment:
      SERVER_PORT: 8000
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: broker:29092

  transaction-service:
    build:
      context: .
      dockerfile: transaction/Dockerfile
    depends_on:
      - db
      - broker
    environment:
      SERVER_PORT: 8000
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/txndb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: broker:29092

  pocket-service:
    build:
      context: .
      dockerfile: pocket/Dockerfile
    depends_on:
      - db
      - broker
    environment:
      SERVER_PORT: 8000
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pocketdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: broker:29092

  gateway:
    image: demo/gateway
    build: ./gateway
    environment:
      - KONG_ADMIN_LISTEN=0.0.0.0:8081
      - KONG_PROXY_LISTEN=0.0.0.0:8080
      - KONG_DATABASE=off
      - KONG_PLUGINS=bundled,custom-jwt-claims-headers

volumes:
  postgres-data: